# Generated by Django 4.2.7 on 2025-10-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название канала')),
                ('username', models.CharField(max_length=100, verbose_name='Username канала')),
                ('url', models.URLField(blank=True, verbose_name='URL канала')),
                ('source_type', models.CharField(choices=[('telegram', 'Telegram')], default='telegram', max_length=20, verbose_name='Тип источника')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_parsed', models.DateTimeField(blank=True, null=True, verbose_name='Последний парсинг')),
            ],
            options={
                'verbose_name': 'Источник новостей',
                'verbose_name_plural': 'Источники новостей',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на новость')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.newssource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['published_date'], name='aggregator__publish_4f1092_idx'), models.Index(fields=['source', 'published_date'], name='aggregator__source__8ed009_idx')],
            },
        ),
    ]
