# Generated by Django 4.2.7 on 2025-10-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='media',
            field=models.BooleanField(default=False, verbose_name='Медиа'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='media_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('none', 'Без медиа')], default='none', max_length=10, verbose_name='Тип медиа'),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='news_media/%Y/%m/%d/', verbose_name='Файл')),
                ('file_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('document', 'Документ'), ('audio', 'Аудио')], max_length=20, verbose_name='Тип файла')),
                ('file_size', models.IntegerField(default=0, verbose_name='Размер файла')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media_thumbnails/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='aggregator.newsitem', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'indexes': [models.Index(fields=['news', 'file_type'], name='aggregator__news_id_751551_idx')],
            },
        ),
    ]
