# Generated by Django 4.2.7 on 2026-04-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_newsitem_media_newsitem_media_type_mediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'indexes': [models.Index(fields=['name'], name='aggregator__name_d67e3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.newsitem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.tag')),
            ],
            options={
                'verbose_name': 'Связь новости и тега',
                'verbose_name_plural': 'Связи новости и тегов',
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news_items', through='aggregator.NewsItemTag', to='aggregator.tag', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='newsitemtag',
            index=models.Index(fields=['news'], name='aggregator__news_id_dc9fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitemtag',
            index=models.Index(fields=['tag'], name='aggregator__tag_id_858156_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsitemtag',
            unique_together={('news', 'tag')},
        ),
    ]
