# Generated by Django 4.2.7 on 2026-05-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_tag_newsitemtag_newsitem_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения обработки'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='processing_error',
            field=models.TextField(blank=True, verbose_name='Ошибка обработки'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('processed', 'Обработано'), ('failed', 'Ошибка обработки')], default='pending', max_length=20, verbose_name='Статус обработки'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='LLM обработка завершена'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='media',
            field=models.BooleanField(default=False, verbose_name='Наличие медиа'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['processing_status'], name='aggregator__process_1f68c4_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['is_processed'], name='aggregator__is_proc_105023_idx'),
        ),
    ]
